### ISSUE TITLE
how to add array plist  ios yml

### ISSUE THREAD

**Issue by productdevbook** [ionic-team/trapeze#103]
```
<key>SKAdNetworkItems</key>
<array>
  <dict>
    <key>SKAdNetworkIdentifier</key>
    <string>cstr6suwn9.skadnetwork</string>
  </dict>
</array>
```

**Comment by Crylion** [comment]
Hey! Next time, please make sure to supply more details on what your problem is and what you already tried to solve it.
But I assume you want to achieve multiple dictionaries in one array?

If you take a look at the [docs of the plist operation](https://trapeze.dev/docs/configuration-tool#plist), there is an example for `CFBundleURLTypes`, which shares the same data structure as `SKAdNetworkItems`.
I did a quick test, and this worked for me to get the data structure you need (with two additional example values for `SKAdNetworkIdentifier` to check if it generates the array correctly. For your example, you would only need the first):

```
 plist:
    - replace: true
      entries:
        - SKAdNetworkItems:
          - SKAdNetworkIdentifier: cstr6suwn9.skadnetwork
          - SKAdNetworkIdentifier: fjkskfhgfn.skadnetwork
          - SKAdNetworkIdentifier: 123456789.skadnetwork
```
