### ISSUE TITLE
Error: no such file or directory, stat 'android/app/src/main/java/MainActivity.java'

### ISSUE THREAD

**Issue by maxfloden** [ionic-team/trapeze#109]
I get this error when running `npx trapeze run trapeze.config.yaml --android-project android --ios-project ios/App`

Output:
```
run ios bundleId com.xxx.yyy
run ios version 2.3.0
run ios incrementBuild 
run android packageName com.xxx.yyy
Fatal error: Error running command
[Error: ENOENT: no such file or directory, stat 'android/app/src/main/java/MainActivity.java'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'android/app/src/main/java/MainActivity.java'
}
```

My yaml file:
```
vars:
  BUNDLE_ID:
    default: com.xxx.yyy
  VERSION:
    default: 2.3.0
platforms:
  ios:
    targets:
      App:
        bundleId: $BUNDLE_ID
        version: $VERSION
        incrementBuild: true
  android:
    packageName: $BUNDLE_ID
    versionName: $VERSION
    incrementVersionCode: true
```

* @trapezedev/configure 5.0.6
* Ionic6 / Capacitor4 project

The MainActivity.java seems to be located in android/app/src/main/java/com/xxx/yyy/MainActivity.java - ie the bundle/package id is part of path.

I cannot find anywhere in the documentation how to specify the file location, so my guess is that it is supposed to work without specifying it?
