### ISSUE TITLE
Download file from external location if source: begins with http/s

### ISSUE THREAD

**Issue by matthewbecker1990** [ionic-team/trapeze#114]
It would be amazing to be able to do something like this

```
    res:
      - path: drawable
        file: icon.png
        source: https://example.com/$BUNDLE_ID/icon.png
```

to grab files dynamically if you are creating multiple projects from the one code base.
