### ISSUE TITLE
android packageName not updating app/build.gradle applicationId

### ISSUE THREAD

**Issue by matthewbecker1990** [ionic-team/trapeze#115]
android packageName not updating app/build.gradle applicationId

```
vars:
  BUNDLE_ID:
    default: com.app.demo
  PACKAGE_NAME:
    default: App Demo

platforms:
  android:
    versionName: 5.2.2
    packageName: $BUNDLE_ID
```

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        applicationId ""
        targetSdkVersion rootProject.ext.targetSdkVersion
```
