### ISSUE TITLE
Support for localized apps

### ISSUE THREAD

**Issue by vscaiceanu-1a** [ionic-team/trapeze#116]
Hello,

Today we can customize strings like app name for single language apps but not for multi language ones.

In a Capacitor app, the folder structure looks like this:
![image](https://user-images.githubusercontent.com/86055112/197565720-5c5539cf-7838-47ba-a2a4-b20d55221048.png)

For the Android part, we could workaround to edit each language specific xml file. On the other hand, we can't modify `.strings` files for iOS.

Would it be possible to add support for localized applications?

Thanks!

**Comment by vscaiceanu-1a** [comment]
I was thinking about having a folder holding OS-specific localiziation files. Something like this:

```
project
│   cap-config.yml
│
└───trapeze-loc
│   │
│   └───android
│   │   │   en.json
│   │   │   fr.json
│   │   │   ...
│   │
│   │
│   └───ios
│       │   en.json
│       │   fr.json
│       │   ...
```
With
`en.json` for android
```json
{
  "app_name": "My app",
  "title_activity_main": "My app",
  "some_custom_label": "Custom label"
}
```

`en.json` for ios
```json
{
  "CFBundleDisplayName": "My app",
  "CustomLabel": "Custom label"
}
```
And the corresponding translations for the other languages.

I considered separate folder for iOS and Android because the trapeze configuration is split per OS. It would allow doing something like this in `cap-config.yml`:

```yaml
platforms:
  ios:
    targets:
      App:
        localizations: trapeze-loc/ios
  android:
    localizations: trapeze-loc/android
```

Since a Capacitor app is mostly a web app, we don't expect many keys in the localisation files so the OS segregation won't be a problem. But since Trapeze is now framework agnostic we should consider an app with many translations. In this case maybe a `common` folder could come in handy to avoid key duplication.


```
project
│   cap-config.yml
│
└───trapeze-loc
│   │
│   └───android
│   │   │   en.json
│   │   │   fr.json
│   │   │   ...
│   │
│   │
│   └───ios
│   │   │   en.json
│   │   │   fr.json
│   │   │   ...
│   │
│   │
│   └───common
│       │   en.json
│       │   fr.json
│       │   ...
```

Having this as an input, Trapeze could generate, for each language,  the `strings.xml` for Android and `InfoPlist.strings` for iOS.

What do you think?

**Comment by mlynch** [comment]
Thanks, I'll have to think more about this. I don't want there to be any trapeze specific files required because one of the goals of the project is that it can work with arbitrary native mobile projects regardless of layout or framework. 

Thinking more about your first example, you actually can do this today by just passing the path of the file to `xml`:

```yaml
      - resFile: values-fr/strings.xml
        target: resources/string[@name="app_name"]
        replace: |
          <string name="app_name">French App Name</string>
```

Will this not work for you?

**Comment by vscaiceanu-1a** [comment]
This can work fine for Android because we can update `xml` files.  AFAIK for iOS we can't update `.strings` files. Would that be possible?

In my case, I am building several flavours of a white-label Capacitor app. To avoid adding the resources files for all the languages in the white label, I was thinking that trapeze can create those files, on the fly, for me.




> I don't want there to be any trapeze specific files required because one of the goals of the project is that it can work with arbitrary native mobile projects regardless of layout or framework.

I think you mean Capacitor specific, right?  In my previous example, I think just the name of my config file is `cap-config.yml` but the folder structure should be framework agnostic.

**Comment by mlynch** [comment]
Working on this right now and I've got a working parser for `.strings` files. I'm thinking of this API, thoughts?

```yaml
platforms:
  ios:
    strings:
      file: Localizable.strings
      set:
        "Insert Element": "Insert element here"
```

**Comment by mlynch** [comment]
To make it easier to use JSON files for this I could also support a different API:

```
platforms:
  ios:
    strings:
      file: Localizable.strings
      setFromJson: path/to/lang.json
```

**Comment by vscaiceanu-1a** [comment]
hi @mlynch 

This will work for us.

What if the file doesn't exist? Can Trapeze create the file? This would be very helpful: the white label app doesn't need to contain localized files for all the languages. You can add them on the fly in the customized app.

Thank you.

**Comment by mlynch** [comment]
Yep the file can definitely be created if it doesn't exist

**Comment by vscaiceanu-1a** [comment]
Hi @mlynch 
I gave it a try and I am facing an issue.

```yaml
        strings:
          - file: App/en.lproj/InfoPlist.strings
            set:
              "CFBundleDisplayName": "My app name"

```

I am getting:
```shell
[warn] Unsupported configuration option ios.strings. Skipping

```

I suspect a problem with publishing the 6.0.7 version as I don't see `ios.strings` in the `operations` array in packages/configure/src/operations/index.ts

https://www.npmjs.com/package/@trapezedev/configure/v/6.0.7?activeTab=explore
