### ISSUE TITLE
PList converting string values to integer

### ISSUE THREAD

**Issue by harleybl** [ionic-team/trapeze#117]
**Goal**: Update the build number for different targets. 

I attempted to do this using the following yml:
```yml
vars:
  CI_BUILD_NUMBER:
    default: '1'

platforms:
  ios:
    buildNumber: $CI_BUILD_NUMBER
    targets:
      Target-QA:
        buildNumber: $CI_BUILD_NUMBER
        plist:
          -replace: true
          file: Target-QA.plist
          entries:
            - CFBundleVersion: $CI_BUILD_NUMBER
```

I would expect the resulting Target-QA.plist file to have this XML if I set the CI_BUILD_NUMBER environment variable to 666:
```xml
<key>CFBundleVersion</key>
<string>666</string>
```

Instead it has:
```xml
<key>CFBundleVersion</key>
<integer>666</integer>
```

Is this a bug or am I doing something wrong?
