### ISSUE TITLE
Support for versionNameSuffix in Android

### ISSUE THREAD

**Issue by basvdijk** [ionic-team/trapeze#136]
In our Android project we set the `versionNameSuffix` to match the environment we're building for. So for example: `1.20-testing` or `1.2.4-production`.

It would be nice if we can set this via the yml

```
vars:
  CI_BUILD_NUMBER:
    default: 1

platforms:
  ios:
    buildNumber: $CI_BUILD_NUMBER
  android:
    versionCode: $CI_BUILD_NUMBER
    versionName: $CI_BUILD_NUMBER
    versionNameSuffix: $CI_ENVIRONMENT
```
