### ISSUE TITLE
Replace of a entry in gradle.variables kills isEqualTo

### ISSUE THREAD

**Issue by Timbuktu1982** [ionic-team/trapeze#157]
Hi there,

when i add a entry in gradle.variables -> ext via insert, all processed correctly.
When i use "replace", the isEqualTo char is killed.

```
 - file: variables.gradle
              target:
                  ext:
              insertType: "variable"
              insert:
                  - firebaseMessagingVersion: "'20.0.6'"
```
All will be processed correctly in target file (firebaseMessagingVersion = '20.0.6').

```
- file: variables.gradle
              target:
                  ext:
                      firebaseMessagingVersion:
              replace:
                  - firebaseMessagingVersion: "'20.0.7'"
```
The command kills the = (firebaseMessagingVersion '20.0.7').

What went wrong?
