### ISSUE TITLE
[question] ios -> How i can delete a attribute from info.plist

### ISSUE THREAD

**Issue by Timbuktu1982** [ionic-team/trapeze#160]
Hi there,

how i can remove an attribute from info.plist completely?

I want to remove "UISupportedInterfaceOrientations~ipad". When i use following command, the attribute contains <null/>.
```
                    - replace: true
                      entries:
                          - UISupportedInterfaceOrientations~ipad:
```

result:
```
		<key>UISupportedInterfaceOrientations~ipad</key>
	        <null/>
```

thx

**Comment by mlynch** [comment]
What if you try an empty array:

```yaml
- replace: true
  entries: []
```

**Comment by Timbuktu1982** [comment]
Great. Thank you very much for the quick support!

**Comment by matfantinel** [comment]
I can't get this to work. Where exactly to I put those lines? I've tried different combinations but just can't figure out how to remove the attribute. In my case, I want to remove "UILaunchStoryboardName"

It feels like the code below might be the closes to what you meant, but it still doesn't work.

```yml
platforms:
  ios:
    targets:
      App:
        plist:
          - UILaunchStoryboardName:
            - replace: true
              entries: []
```
