### ISSUE TITLE
Wrong output for ios -> "CFBundleDocumentTypes"

### ISSUE THREAD

**Issue by Timbuktu1982** [ionic-team/trapeze#162]
Hi there, 
what went wrong?

yaml:

```yaml
  - replace: true
    entries:
        - CFBundleDocumentTypes:
            - CFBundleTypeName: PDF
            - LSHandlerRank: Alternate
            - LSItemContentTypes:
                  - com.adobe.pdf
```
output:
```xml
	<key>CFBundleDocumentTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeName</key>
			<string>PDF</string>
		</dict>
		<dict>
			<key>LSHandlerRank</key>
			<string>Alternate</string>
		</dict>
		<dict>
			<key>LSItemContentTypes</key>
			<array>
				<string>com.adobe.pdf</string>
			</array>
		</dict>
	</array>
```
expected output:
```xml
<key>CFBundleDocumentTypes</key>
	<array>
        <dict>
            <key>CFBundleTypeName</key>
            <string>PDF</string>
            <key>LSHandlerRank</key>
            <string>Alternate</string>
            <key>LSItemContentTypes</key>
            <array>
                <string>com.adobe.pdf</string>
            </array>
        </dict>
	</array>
```

**Comment by mlynch** [comment]
```yaml
  - replace: true
    entries:
        - CFBundleDocumentTypes:
            - CFBundleTypeName: PDF
            - LSHandlerRank: Alternate
            - LSItemContentTypes:
                  - com.adobe.pdf
 ```

This creates an object of the shape:

```json
[
  {
     "CFBundleDocumentTypes": [
       { "CFBundleTypeName": },
     ]
  }
]
```

If you want a different shape, change the yaml:

```
  - replace: true
    entries:
        - CFBundleDocumentTypes:
            CFBundleTypeName: PDF
            LSHandlerRank: Alternate
            LSItemContentTypes:
                - com.adobe.pdf
```

**Comment by Timbuktu1982** [comment]
Great. Thank you very much for the quick support!

**Comment by Timbuktu1982** [comment]
Sorry, i was to fast with closing...
The inner object is correctly now. But i miss the array outside.

yaml:
```
                    - replace: true
                      entries:
                          - CFBundleDocumentTypes:
                                CFBundleTypeName: PDF
                                LSHandlerRank: Alternate
                                LSItemContentTypes:
                                    - com.adobe.pdf
```

output:
```
<key>CFBundleDocumentTypes</key>
	<dict>
		<key>CFBundleTypeName</key>
		<string>PDF</string>
		<key>LSHandlerRank</key>
		<string>Alternate</string>
		<key>LSItemContentTypes</key>
		<array>
			<string>com.adobe.pdf</string>
		</array>
	</dict>
```
expected output:
```
<key>CFBundleDocumentTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeName</key>
            <string>PDF</string>
            <key>LSHandlerRank</key>
            <string>Alternate</string>
            <key>LSItemContentTypes</key>
            <array>
                <string>com.adobe.pdf</string>
            </array>
        </dict>
	<array/>
```

**Comment by Timbuktu1982** [comment]
Ah ok, i have adjust the shape like this and it works great. THX

```
                    - replace: true
                      entries:
                          - CFBundleDocumentTypes:
                                - CFBundleTypeName: PDF
                                  LSHandlerRank: Alternate
                                  LSItemContentTypes:
                                      - com.adobe.pdf

```
