### ISSUE TITLE
platforms/android/versionCode isn't working for me in v7.0.6

### ISSUE THREAD

**Issue by boozedog** [ionic-team/trapeze#164]
No matter what value I set, I always end up with a `versionCode=1` in my `app/build.gradle`
```yaml
vars:
  CI_BUILD_NUMBER:

platforms:
  android:
    versionCode: $CI_BUILD_NUMBER
```

This works:
```yaml
vars:
  CI_BUILD_NUMBER:

platforms:
  android:
    gradle:
      - file: app/build.gradle
        target:
          android:
            defaultConfig:
              versionCode:
        replace:
          versionCode: $CI_BUILD_NUMBER
```
Version:
```
% npx trapeze --version
7.0.6
```
