### ISSUE TITLE
Can't seem to combine ios/targets with other stuff in AppFlow

### ISSUE THREAD

**Issue by boozedog** [ionic-team/trapeze#165]
Works in AppFlow:
```yaml
vars:
  BUNDLE_ID:
  CI_BUILD_NUMBER:
  PACKAGE_VERSION:

platforms:
  ios:
    bundleId: $BUNDLE_ID
    version: $PACKAGE_VERSION
    buildNumber: $CI_BUILD_NUMBER
```

Doesn't work in AppFlow (version gets set, but buildNumber does not)
```yaml
vars:
  BUNDLE_ID:
  CI_BUILD_NUMBER:
  PACKAGE_VERSION:

platforms:
  ios:
    bundleId: $BUNDLE_ID
    version: $PACKAGE_VERSION
    buildNumber: $CI_BUILD_NUMBER
    targets:
      App:
        plist:
          - replace: true
            entries:
              - ITSAppUsesNonExemptEncryption:
                  false
```

Version:
```
% npx trapeze --version
7.0.6
```
