### ISSUE TITLE
iOS Display name

### ISSUE THREAD

**Issue by brilliantinsane** [ionic-team/trapeze#189]
```
  ios:
    targets:
      App:
        displayName: Test App Name
```

I have this in my `config.yaml` file, when I run it, in the console I see following:
`run ios displayName Test App Name`

But, nothing changes in `Info.plist` file. 

This might be due to the fact that I am getting a warning in the console:
`[warn] Skipping ios.displayName (Target 'App' not found in project)`
But I don't see a reason why. I am only putting `Test App Name`, nothing special.

Any ideas?
