### ISSUE TITLE
Bug: appName has no effect (android, capacitor V5)

### ISSUE THREAD

**Issue by tobiasmuecksch** [ionic-team/trapeze#191]
## Description

This issue is explicitly about android.
I'm trying to manipulate the app name with trapeze. According to the docs `appName` is the way to go.
Therefore I've set an appName like this:

```yml
vars:
  APP_NAME:
    default: cap5 Test App
  PACKAGE_NAME_ANDROID:
    default: de.tobiasmuecksch.cap5test

platforms:
  android:
    appName: $APP_NAME
    packageName: $PACKAGE_NAME_ANDROID
    versionName: 2.3.12
    versionCode: 255
```

But when I deploy the app, it still has the previous name, instead of expected `cap5 Test App`.
Of course this time I tried clean project, rebuild project, and cache invalidation, before I opened this issue.

![image](https://github.com/ionic-team/trapeze/assets/1294854/2caf1249-71de-46dc-8cb5-1d3b1d8d0536)

## Versions

Trapeze: 7.0.10
Capacitor: 5.0.0

## Reproduction

1. Clone Repo: https://github.com/tobiasmuecksch/cap5-trapeze-bug
2. Install dependencies `npm i` 
3. run `ionic cap sync`
4. run `npx @trapezedev/configure run platform-config.yml`
5. run `ionic cap open android`
6. clean project, rebuild the project, invalidate caches and restart Android Studio
7. Start the app in an emulator
8. See the aforementioned bug

**Comment by tobiasmuecksch** [comment]
After some investigation, I found out, that if I alter `title_activity_main` in `android/app/src/main/res/values/strings.xml`, the name is applied correctly, which leads me to the conclusion, that trapeze should alter this too.

<img width="1256" alt="image" src="https://github.com/ionic-team/trapeze/assets/1294854/0c0f562e-a93e-42e3-bf67-10ac94b07c7c">

Additionally we can observe, that `package_name` is not correctly changed too.

**Comment by tobiasmuecksch** [comment]
@selcuk-sahin Well, according to the documentation Trapeze already changes the `strings.xml` automatically, when in the manifest there is a reference to this file.

<img width="1398" alt="image" src="https://github.com/ionic-team/trapeze/assets/1294854/e16cb459-cee5-4ee5-988a-76cef5f5a0e2">

Source: https://trapeze.dev/docs/Operations/android#appname

Thank you anyways, for this temporary workaround.

**Comment by selcuk-sahin** [comment]
> @selcuk-sahin Well, according to the documentation Trapeze already changes the `strings.xml` automatically, when in the manifest there is a reference to this file.
> 
> <img alt="image" width="1398" src="https://user-images.githubusercontent.com/1294854/239218465-e16cb459-cee5-4ee5-988a-76cef5f5a0e2.png">
> Source: https://trapeze.dev/docs/Operations/android#appname
> 
> Thank you anyways, for this temporary workaround.

Thanks for that, I didn't recognize the documentation has that info.

**Comment by tobiasmuecksch** [comment]
@mlynch No. Trapeze does not work as expected. It should update the variables in the strings.xml (as described in the documentation), but currently it does not update them.

**Comment by mlynch** [comment]
Hmm, tests for this are passing locally. I wonder if there's some difference in the structure of the app that causes it to not work.

**Comment by mlynch** [comment]
I'm having a hard time following the thread, are you saying that trapeze should also update `title_activity_main`? You are correct, it's not doing it. But you *are* seeing it update `app_name` in `strings.xml`, correct?

**Comment by tobiasmuecksch** [comment]
No. In my case `strings.xml` remains unchanged. That's the problem I've tried to describe.

Feel free to try the provided reproduction repository. 

You could also try to remove the android platform and freshly re add it to your test environment. I assume, that something has changed in the project structure in the past few updates.

**Comment by tobiasmuecksch** [comment]
@mlynch Have you been able to reproduce the error, or can I help you somehow?

**Comment by mlynch** [comment]
Just tested it in your app and it works fine for me:

<img width="459" alt="image" src="https://github.com/ionic-team/trapeze/assets/11214/4f42d955-6a09-4b18-a63d-4d467a8b34d2">

**Comment by tobiasmuecksch** [comment]
@mlynch Yes, but have you started this app in the emulator and inspected it's name in the programs menu? You will see, that `app_name` does not have the expected effect on the app's name anymore.

I found out that trapeze should also change `title_activity_main`.
I'm sorry, I already mentioned that in https://github.com/ionic-team/trapeze/issues/191#issuecomment-1550257012 but didn't forgot to re-add this information to my prior comment.

**Comment by tobiasmuecksch** [comment]
@mlynch P.S.: is it expected behavior, that `package_name` remains unchanged in `strings.xml`

**Comment by mlynch** [comment]
Okay so we need to just have a broader discussion about what `appName` should do. I have tested your app locally and I see the `app_name` change taking effect, but the issue here is more about what the OS is displaying and where, and what `appName` _should_ modify. Right now it's not modifying the main Activity name as well, maybe it should?

**Comment by mlynch** [comment]
> @mlynch P.S.: is it expected behavior, that `package_name` remains unchanged in `strings.xml`?

I assume you mean when changing the package name? Right now it doesn't look like that string is actually being used anywhere so the tool wouldn't change it. Trapeze is agnostic of the mobile framework so it tries to not assume random strings mean anything in your res files. We can have a separate discussion about package name changes though in a different issue.

**Comment by tobiasmuecksch** [comment]
@mlynch Thank you for your in-depth responses.

Regarding `app_name`:
Until I updated my app to capacitor 5, the `app_name` setting also affected the name, which was displayed in the home screen underneath the icon (see first screenshot in the issue). Since this behavior has changed I was confused and thought it would be a bug. But now I do understand why this is not a bug.

In my opinion, developers should at least have a simple option to manipulate the app displayed name. While keeping in mind what you said about Trapeze's agnosticism, I'd suggest to handle it similar to iOS (where we have a `displayName` and a `productName` option). But I'm not quite sure how to name it. How about `title_activity`?


Regarding `package_name`:
As I'm not very experienced in android development, I only made this observation without understanding whether it has any effect or not. At first sight it seemed odd to me.
I'll take some more time to investigate and understand this topic further and create a new issue, in case I still think it's somehow relevant.

**Comment by gerhardcit** [comment]
> ```yaml
> xml:
>       #strings.xml
>       - resFile: values/strings.xml
>         target: resources/string[@name="app_name"]
>         replace: |
>           <string name="app_name">$APP_NAME</string>
> ```

At some point this get's worse. when you try and change an app name after Android built it.

```
npx trapeze run env/app1.yaml 
run android packageName com.amazing.appone
Fatal error: Error running command
Error: Current Java package name and directory structure do not match the <manifest> package attribute. Ensure these match before modifying the project package name
    at AndroidProject.setPackageName (/testing/capacitor2/node_modules/@trapezedev/project/dist/android/project.js:132:19)
    at async executeOperations (/testing/capacitor2/node_modules/@trapezedev/configure/dist/tasks/run.js:52:10)
    at async runCommand (/testing/capacitor2/node_modules/@trapezedev/configure/dist/tasks/run.js:31:9)
    at async /testing/capacitor2/node_modules/@trapezedev/configure/dist/index.js:58:13
    at async Command.<anonymous> (/testing/capacitor2/node_modules/@trapezedev/configure/dist/util/cli.js:31:13)
```

Surely the idea of this is that you can have one app source (javascript, css etc) and build different app store apps.. ie: Whitelabeling..
I also went with the documentation which does not appear to do what it says it does.
Without being able to change the app name.. Trapeze becomes completely useless to us.

**Comment by gerhardcit** [comment]
I ended up doing something like this in the config-app1.yaml file 
```yaml
vars:
  BUNDLE_ID:
    default: com.amazing.appone
  PACKAGE_NAME:
    default: com.amazing.appone
  APP_NAME:
    default: App One
platforms:
  android:
    packageName: $PACKAGE_NAME
    appName: $APP_NAME
    versionName: 1.1.1
    versionCode: 111
    xml:
      #strings.xml
      - resFile: values/strings.xml
        target: resources/string[@name="app_name"]
        replace: |
          <string name="app_name">$APP_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="title_activity_main"]
        replace: |
          <string name="title_activity_main">$APP_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="package_name"]
        replace: |
          <string name="package_name">$PACKAGE_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="custom_url_scheme"]
        replace: |
          <string name="custom_url_scheme">$PACKAGE_NAME</string>
```

that produces this output: 
android/app/src/main/res/values/strings.xml

```xml
<?xml version='1.0' encoding='utf-8' ?>
<resources>
    <string name="app_name">App One</string>
    <string name="title_activity_main">App One</string>
    <string name="package_name">com.amazing.appone</string>
    <string name="custom_url_scheme">com.amazing.appone</string>
</resources>
```

then there is an equivalent for config-app2.yaml
`npx trapeze run config-app2.yaml -y` should change all of appone to apptwo

BUT trapeze does not update the capacitor.config.json or capacitor.config.ts
so you would have to manually fix this somehow.

I'm surprised at how capacitor does not understand multi tenant apps from the same source base. Is it that unique?

**Comment by hcassar93** [comment]
I just spent hours trying to figure out this exact issue. 

Then found this.. silly me 🤦‍♂️

I think @tobiasmuecksch is dead on and his proposal to set title_activity makes sense. 

@gerhardcit's solution doesn't work for me as I'm using the project API. 

@mlynch thanks for your thoughtful discussion on this thread and generally for your work on ionic and capacitor.

**Comment by emelampianakis** [comment]
> I ended up doing something like this in the config-app1.yaml file
> 
> ```yaml
> vars:
>   BUNDLE_ID:
>     default: com.amazing.appone
>   PACKAGE_NAME:
>     default: com.amazing.appone
>   APP_NAME:
>     default: App One
> platforms:
>   android:
>     packageName: $PACKAGE_NAME
>     appName: $APP_NAME
>     versionName: 1.1.1
>     versionCode: 111
>     xml:
>       #strings.xml
>       - resFile: values/strings.xml
>         target: resources/string[@name="app_name"]
>         replace: |
>           <string name="app_name">$APP_NAME</string>
>       - resFile: values/strings.xml
>         target: resources/string[@name="title_activity_main"]
>         replace: |
>           <string name="title_activity_main">$APP_NAME</string>
>       - resFile: values/strings.xml
>         target: resources/string[@name="package_name"]
>         replace: |
>           <string name="package_name">$PACKAGE_NAME</string>
>       - resFile: values/strings.xml
>         target: resources/string[@name="custom_url_scheme"]
>         replace: |
>           <string name="custom_url_scheme">$PACKAGE_NAME</string>
> ```
> 
> that produces this output: android/app/src/main/res/values/strings.xml
> 
> ```
> <?xml version='1.0' encoding='utf-8' ?>
> <resources>
>     <string name="app_name">App One</string>
>     <string name="title_activity_main">App One</string>
>     <string name="package_name">com.amazing.appone</string>
>     <string name="custom_url_scheme">com.amazing.appone</string>
> </resources>
> ```
> 
> then there is an equivalent for config-app2.yaml `npx trapeze run config-app2.yaml -y` should change all of appone to apptwo
> 
> BUT trapeze does not update the capacitor.config.json or capacitor.config.ts so you would have to manually fix this somehow.
> 
> I'm surprised at how capacitor does not understand multi tenant apps from the same source base. Is it that unique?

I am building capacitor whitelabel apps using capacitor@4for some time now. The trick is to update the string values **after you build & sync the app** so the appId and appName in capacitor config do not really matter (correct me if I'm wrong). 
This is what I'm replacing:

```
android:
    packageName: $PACKAGE_NAME
    versionName: $VERSION
    versionCode: $ANDROID_VERSION_CODE
    xml:
      - resFile: values/strings.xml
        target: resources/string[@name="app_name"]
        replace: |
          <string name="app_name">$APP_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="title_activity_main"]
        replace: |
          <string name="title_activity_main">$APP_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="package_name"]
        replace: |
          <string name="package_name">$PACKAGE_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="custom_url_scheme"]
        replace: |
          <string name="custom_url_scheme">$PACKAGE_NAME</string>
          
ios:
    targets:
      App:
        bundleId: $BUNDLE_ID
        version: $VERSION
        buildNumber: $IOS_BUILD_NUMBER
        productName: $APP_NAME
        displayName: $APP_NAME
```

However with the capacitor@5 changes I encountered the same error as you regarding the manifest. The steps I used to solve it:

- delete android platform and add it again 

the major diff I noticed in the manifest is 
```
-      android:name="com.example.app.MainActivity"
+      android:name=".MainActivity"
```
- add android platform & transfer any native changes I had previously
now trapeze is working as intended and com.example.app is replaced with my 'com.amazing.appone' everywhere
