### ISSUE TITLE
Error: Unable to load or parse gradle file: Error (on Windows, but on Mac is okay)

### ISSUE THREAD

**Issue by hughknaus** [ionic-team/trapeze#192]
This fails on Windows but works on Mac, my first guess was that I had different versions of Java or Android Studio installed but both are running the same versions.  

Running 'VERSION_MAJOR_MINOR=8.16 VERSION_COUNTER=12 BUNDLE_VERSION=8.16.12 BUNDLE_SHORT_VERSION=8.16.12 VERSION_CODE=8160012 npx @trapezedev/configure run ../trapeze.config.yaml --android-project android -y'

My trapeze.config.yaml is fairly simple:
```
vars:
  BUNDLE_ID:
    default: com.myapp
  PACKAGE_NAME:
    default: com.myapp
  BUNDLE_VERSION:
    default: 1.0.0
  BUNDLE_SHORT_VERSION:
    default: 1.0.0
  VERSION_MAJOR_MINOR:
    default: 1.0
  VERSION_COUNTER:
    default: 0
  VERSION_CODE:
    default: 100

platforms:
  ios:
    targets:
      App:
        bundleId: $BUNDLE_ID
        version: $VERSION_MAJOR_MINOR
        buildNumber: $VERSION_COUNTER
        productName: com.myapp
        displayName: com.myapp

        buildSettings:
          ENABLE_BITCODE: false
          STRIP_SWIFT_SYMBOLS: false

        plist:
          replace: true
          entries:
            - CFBundleDevelopmentRegion: en_US
            - CFBundleName: com.myapp
            - CFBundleVersion: $BUNDLE_VERSION
            - CFBundleShortVersionString: $BUNDLE_VERSION
            - NSCameraUsageDescription: This lets you take photos to document the damages to the property.
            - NSPhotoLibraryUsageDescription: This lets you attach photos from your photo library to document the damages to the property.
            - NSPhotoLibraryAddUsageDescription: This lets us save photos to your photo library in order to facilitate uploading of the photos.
            - ITSAppUsesNonExemptEncryption: false
            - UIUserInterfaceStyle: Light
            - UISupportedInterfaceOrientations: [ UIInterfaceOrientationPortrait ]
            - UISupportedInterfaceOrientations~ipad: [ UIInterfaceOrientationPortrait ]
            - UIRequiresFullScreen: true

  android:
    packageName: $PACKAGE_NAME
    versionName: $BUNDLE_VERSION
    versionCode: $VERSION_CODE
    
    manifest:
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
          
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <queries>
            <intent>
              <action android:name="android.media.action.IMAGE_CAPTURE"/>
            </intent>
            <intent>
              <action android:name="android.intent.action.GET_CONTENT"/>
            </intent>
            <intent>
              <action android:name="android.intent.action.PICK"/>
            </intent>
            <intent>
              <action android:name="com.android.camera.action.CROP"/>
              <data android:mimeType="image/*" android:scheme="content"/>
            </intent>
          </queries>

      - file: AndroidManifest.xml
        target: manifest/application/activity
        attrs:
          android:screenOrientation: portrait
```

Error:
```
skip ios bundleId com.myapp
skip ios version 8.16
skip ios buildNumber 12
skip ios productName myapp
skip ios displayName myapp
skip ios buildSettings ENABLE_BITCODE = false, STRIP_SWIFT_SYMBOLS = false
skip ios plist 12 modifications
run android packageName com.myapp
run android versionName 8.16.12
Fatal error: Error running command
Error: Unable to load or parse gradle file: Error: spawn C:\Program Files\Git\Library\Java\JavaVirtualMachines\jdk-15.0.2.jdk\Contents\Home\bin\java ENOENT
    at GradleFile.parse (C:\Users\hknaus\AppData\Local\npm-cache\_npx\14f6b2623fe0959a\node_modules\@trapezedev\project\dist\android\gradle-file.js:228:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GradleFile.replaceProperties (C:\Users\hknaus\AppData\Local\npm-cache\_npx\14f6b2623fe0959a\node_modules\@trapezedev\project\dist\android\gradle-file.js:53:9)
    at async executeOperations (C:\Users\hknaus\AppData\Local\npm-cache\_npx\14f6b2623fe0959a\node_modules\@trapezedev\configure\dist\tasks\run.js:52:10)
    at async runCommand (C:\Users\hknaus\AppData\Local\npm-cache\_npx\14f6b2623fe0959a\node_modules\@trapezedev\configure\dist\tasks\run.js:31:9)
    at async C:\Users\hknaus\AppData\Local\npm-cache\_npx\14f6b2623fe0959a\node_modules\@trapezedev\configure\dist\index.js:58:13
    at async Command.<anonymous> (C:\Users\hknaus\AppData\Local\npm-cache\_npx\14f6b2623fe0959a\node_modules\@trapezedev\configure\dist\util\cli.js:31:13)
```

And the `build.gradle file` is in the `android` folder.
