### ISSUE TITLE
Plist & Entitlements have different replace syntax in YAML file

### ISSUE THREAD

**Issue by selcuk-sahin** [ionic-team/trapeze#193]
Problem:

on the `plist` entry, we are using `-` before replace, but on the entitlements we don't use it. It would be easier to grasp if both follow the same syntax, since both edits plist files.

```yaml
        plist:
          - replace: true 
            entries:
            - CFBundleDisplayName: $APP_NAME
          - FacebookAppID: $FACEBOOK_APP_ID

        entitlements:
          replace: true 
          entries:
          - com.apple.developer.associated-domains: ["applinks:$WEBSITE_HOST_NAME", "applinks:$DYNAMIC_LINK_HOST_NAME"]
          - com.apple.security.application-groups: ["group.$BUNDLE_ID.onesignal"]
```
