### ISSUE TITLE
Specify the Xcode signing team using `config.yaml`?

### ISSUE THREAD

**Issue by elliotwaite** [ionic-team/trapeze#194]
Is there a way to specify the Xcode signing team using the Trapeze `config.yaml` file?

I currently set it through the Xcode app like this:
1. Show the Project Navigator (⌘1)
2. Select the "App" project
3. Select the "App" target
4. Select the "Signing & Capabilities" tab
5. Use the "Team" dropdown menu to select the team

**Comment by mlynch** [comment]
Should be doable, seems like it's just setting flags in `pbxproj`. Would need to think about how best to expose generic pbxproj operations

**Comment by gtbuchanan** [comment]
This is what I use:
```yaml
platforms:
  ios:
    buildSettings:
      DEVELOPMENT_TEAM: ABCDE12345
```
