### ISSUE TITLE
Add a file to XCode Project (e.g., GoogleService-Info.plist)

### ISSUE THREAD

**Issue by Dr-Zhi** [ionic-team/trapeze#196]
Hi,

I'm wondering if there is a way to add a file to XCode project programmatically? Using `copy` is not sufficient, as XCode does not automatically recognize the new file in its folder. Thanks! 

```
platforms:
  ios:
    targets:
      App:
        copy:
          - src: ../firebase/GoogleService-Info.plist
            dest: App/GoogleService-Info.plist
```
