### ISSUE TITLE
Best practice for merging in root of Android manifest?

### ISSUE THREAD

**Issue by boozedog** [ionic-team/trapeze#202]
I'd like to merge the following:

```xml
          <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
          <uses-feature android:name="android.hardware.location.gps" />
          <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

... into the root `<manifest/>` root node so that the result looks like this:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
   ...
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-feature android:name="android.hardware.location.gps" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>
```

What's best practice for doing this in trapeze? I don't think I can use manifest: merge as it "requires a matching sub-tree root node to be provided" https://trapeze.dev/docs/Operations/android#manifest

**Comment by boozedog** [comment]
Hello? :sweat_smile:

**Comment by robingenz** [comment]
You can use `merge` here — the "matching root node" is just `<manifest>` itself:

```yaml
platforms:
  android:
    manifest:
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <manifest>
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
            <uses-feature android:name="android.hardware.location.gps" />
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
          </manifest>
```

We verified this adds the nodes to the root and does not duplicate them when run again. `inject` with `target: manifest` also works but appends every time, so `merge` is the better choice for repeated CI runs. We'll add a root-level example to the docs. Closing as answered.
