### ISSUE TITLE
How to specify provisioning profile in .yaml config file

### ISSUE THREAD

**Issue by BastienCivel** [ionic-team/trapeze#209]
Hello,

I have a mobile application in Angular ionic with capacitor, and it uses trapeze for the CI/CD.
I have trouble understanding how can I specify the provisioning profile directly from the .yaml config file ?
I'd like my .pbxproj file to have the correct profile after the trapeze build or any other way that would let me do it.

Thanks in advance !

**Comment by gtbuchanan** [comment]
Here's what I ended up with:
```yaml
platforms:
  ios:
    targets:
      builds:
        Release:
          buildSettings:
            CODE_SIGN_STYLE: Manual
            CODE_SIGN_IDENTITY: iPhone Distribution
            DEVELOPMENT_TEAM: ABCDE12345
            PROVISIONING_PROFILE_SPECIFIER: My Profile
```

**Comment by robingenz** [comment]
You can set this with the `ios.buildSettings` operation, which writes straight into the pbxproj build settings for the target/build you name:

```yaml
platforms:
  ios:
    targets:
      App:
        builds:
          Release:
            buildSettings:
              CODE_SIGN_STYLE: Manual
              DEVELOPMENT_TEAM: ABCDE12345
              CODE_SIGN_IDENTITY: iPhone Distribution
              PROVISIONING_PROFILE_SPECIFIER: My Profile
```

Note the target name (`App`) is required above `builds`. We'll add a signing example to the docs. Closing this as answered.
