### ISSUE TITLE
Feature request: Enable android `productFlavors`

### ISSUE THREAD

**Issue by samanthaandrews** [ionic-team/trapeze#213]
I'm working on a project that uses `productFlavors` to set the versionName in our android app. It would be nice if Trapeze supported productFlavors so that we could update the versionName in one file for iOS and Android apps.

<img width="581" alt="Screenshot 2024-02-27 at 10 12 40 AM" src="https://github.com/ionic-team/trapeze/assets/34348332/f0f91643-18e3-460a-916a-ae9a4039f8c0">

**Comment by robingenz** [comment]
This already works with the generic `gradle` operation — the `target` path object can address any nested block, including a product flavor:

```yaml
platforms:
  android:
    gradle:
      - file: app/build.gradle
        target:
          android:
            productFlavors:
              prod:
                versionName:
        replace:
          versionName: "'$VERSION_NAME'"
  ios:
    version: $VERSION_NAME
```

We verified this against a build.gradle with two flavors: only the targeted flavor is rewritten, and the same `$VERSION_NAME` var can drive the iOS version in the same run. The `versionName`/`versionCode` shorthands only ever target `defaultConfig`, which is why they looked like they didn't support flavors. Closing, but let us know if this doesn't fit your setup.
