### ISSUE TITLE
Replacement encodes special characters

### ISSUE THREAD

**Issue by carlvorster** [ionic-team/trapeze#220]
I'm trying to inject the following into my Info.plist file to force the space in the name, but is seems Trapeze is converting & to &amp; - any idea how to escape this conversion? I've tried , \, quotes

**.yml**
```
ios:
    targets:
      App:
        version: $VERSION
        incrementBuild: true
        bundleId: $BUNDLE_ID
        displayName: STAGING&#x2008;Market
```

**info.plist**
```
<key>CFBundleDisplayName</key>
<string>STAGING&amp;#x2008;Market</string> 
```
