### ISSUE TITLE
Support other plist files

### ISSUE THREAD

**Issue by bocodigital** [ionic-team/trapeze#52]
It would be great to use this to update the GoogleService-Info.plist file commonly used for Firebase projects.

**Comment by mlynch** [comment]
Yes this should be pretty easy to support, will add it to the roadmap

**Comment by bocodigital** [comment]
Awesome thank you!!

**Comment by EinfachHans** [comment]
Would be awesome!

**Comment by mlynch** [comment]
This will be the next feature to land. Follow this branch for more: https://github.com/ionic-team/trapeze/tree/plist

**Comment by mlynch** [comment]
Okay this is shipped in a pre-release, can you give `@trapezedev/configure@next` a try? Should be `4.0.0-next.1` or later.

Here's how you can use it:

```yaml
        plist:
          - replace: true
            file: GoogleService-Info.plist
            entries:
              - UISupportedInterfaceOrientations:
                  - UIInterfaceOrientationPortrait
```
