### ISSUE TITLE
feat: generate for pwa apple-app-site-association

### ISSUE THREAD

**Issue by reslear** [ionic-team/trapeze#65]
hi @mlynch i'm suggest add feature for generate pwa `/.well-known/apple-app-site-association` example: 

```yml
vars:
  BUNDLE_ID:
    default: io.ionic.wowzaStarter
  PACKAGE_NAME:
    default: io.ionic.wowzaStarter
  TEAM_ID:
    default: MMR96SV2R9

platforms:
  ios:
    targets:
      App:
        entitlements:
          - com.apple.developer.associated-domains:
            - applinks:app.$(DOMAIN)
  pwa:
    apple-app-site-association:
        path: ./public/.well-known/apple-app-site-association
        content:    
            applinks:
                apps: []
                details:
                    - appID: $(TEAM_ID).$(BUNDLE_ID)
                paths:
                    - '*'
```

output `public/.well-known/apple-app-site-association` :
```json
{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "MMR96SV2R9.io.ionic.wowzaStarter",
        "paths": [
          "*"
        ]
      }
    ]
  }
}
``` 

or is it better to suggest this feature to https://github.com/ionic-team/capacitor-assets ?

**Comment by mlynch** [comment]
This seems very reasonable. I'd probably lump this under the json support I shipped recently but this reminds me we need a pwa platform

**Comment by robingenz** [comment]
This works today with the `project.json` operation — it writes arbitrary JSON anywhere under the project root, creates the file and any missing directories, and interpolates vars:

```yaml
project:
  json:
    - file: public/.well-known/apple-app-site-association
      set:
        applinks:
          apps: []
          details:
            - appID: $TEAM_ID.$BUNDLE_ID
              paths: ['*']
```

We verified it produces exactly the output in your example, so a separate `pwa` platform would only be sugar over this. Closing — thanks for the suggestion.
