### ISSUE TITLE
Android Gradle cannot insert to dependencies

### ISSUE THREAD

**Issue by hiiimgary** [ionic-team/trapeze#69]
Hi @mlynch,

I was trying to inject a dependency into the capacitor-cordova-android-plugins/build.gradle file, but the capacitor configure always finds the buildscripts/dependencies instead of the root dependencies.

config.yaml:
```
platforms:
  ios:
    targets:
      App:
        bundleId: $BUNDLE_ID
  android:
    packageName: $PACKAGE_NAME
    gradle:
      - file: capacitor-cordova-android-plugins/build.gradle
        target:
          dependencies:
        insert:
          - implementation: "'androidx.core:core:1.3.2'"
```

running the capacitor configure command will modify the gradle file like this:

```
ext {
    cordovaAndroidVersion = project.hasProperty('cordovaAndroidVersion') ? rootProject.ext.cordovaAndroidVersion : '7.0.0'
}

buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.1'
        implementation 'androidx.core:core:1.3.2' <--- Inserts it here instead of the root dependencies object
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 30
    defaultConfig {
        minSdkVersion project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 21
        targetSdkVersion project.hasProperty('targetSdkVersion') ? rootProject.ext.targetSdkVersion : 30
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    google()
    jcenter()
    mavenCentral()
    flatDir{
        dirs 'src/main/libs', 'libs'
    }
}

dependencies {
    implementation fileTree(dir: 'src/main/libs', include: ['*.jar'])
    implementation "org.apache.cordova:framework:$cordovaAndroidVersion"
    // SUB-PROJECT DEPENDENCIES START
    <------ I wanted to insert the implementation here.
    // SUB-PROJECT DEPENDENCIES END
}

// PLUGIN GRADLE EXTENSIONS START
apply from: "cordova.variables.gradle"
// PLUGIN GRADLE EXTENSIONS END

for (def func : cdvPluginPostBuildExtras) {
    func()
}
```
