### ISSUE TITLE
Add attributes to AndroidManifest.xml

### ISSUE THREAD

**Issue by marioshtika** [ionic-team/trapeze#80]
Hello,

I am trying to add a new attribute `android:exported="true"` to an existing node `<receiver>` in the AndroidManifest.xml.
FYI: There are multiple `<receiver>` nodes in the AndroidManifest.xml file so I am selecting the specific node using XPath.

What it is right now
```
<?xml version='1.0' encoding='utf-8'?>
<manifest>
    <application>
        ...
        <receiver android:enabled="true" android:name="nl.xservices.plugins.ShareChooserPendingIntent">
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
            </intent-filter>
        </receiver>
        ...
    </application>
</manifest>
```

What I want it to be
```
<?xml version='1.0' encoding='utf-8'?>
<manifest>
    <application>
        ...
        <receiver android:enabled="true" android:exported="true" android:name="nl.xservices.plugins.ShareChooserPendingIntent">
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
            </intent-filter>
        </receiver>
        ...
    </application>
</manifest>
```

I have tried everything but it looks like can not add a new attribute to a specific node.

Using `attrs`

```
platforms:
  android:
    manifest:
      - file: AndroidManifest.xml
        target: manifest/application/receiver[@android:name="nl.xservices.plugins.ShareChooserPendingIntent"]
        attrs:
          android:exported: true
```

Using `merge`

```
platforms:
  android:
    manifest:
      - file: AndroidManifest.xml
        target: manifest/application/receiver[@android:name="nl.xservices.plugins.ShareChooserPendingIntent"]
        merge: |
          <receiver android:enabled="true" android:exported="true" android:name="nl.xservices.plugins.ShareChooserPendingIntent">
            <intent-filter>
              <action android:name="android.intent.action.SEND" />
            </intent-filter>
          </receiver>
```

Using `delete`

```
platforms:
  android:
    manifest:
      - file: AndroidManifest.xml
        delete: manifest/application/receiver[@android:name="nl.xservices.plugins.ShareChooserPendingIntent"]
```

Am I doing something wrong? Or is it a bug in there? Or is this something that is not supported?

Thank you in advance.
