### ISSUE TITLE
Support array variables for json

### ISSUE THREAD

**Issue by vscaiceanu-1a** [ionic-team/trapeze#86]
Hello,

I am trying to update the `allowNavigation` in both iOS and Android `capacitor.config.json`.

I am using `4.0.0-next.2`.

If I set the array as a value it works as expected

```yaml
platforms:
  ios:
    targets:
        json:
          - file: App/capacitor.config.json
            set:
              server:
                allowNavigation: ['trapeze.dev', 'capacitorjs.com']
  android:
    json:
      - file: app/src/main/assets/capacitor.config.json
        set:
          server:
                allowNavigation: ['trapeze.dev', 'capacitorjs.com']
```

However, I would like to factorise the array in a variable since I always have the same domains for both iOS and Android.

```yaml
vars:
  ALLOWED_DOMAINS:
    default:
      - ['trapeze.dev', 'capacitorjs.com']
platforms:
  ios:
    targets:
        json:
          - file: App/capacitor.config.json
            set:
              server:
                allowNavigation: $ALLOWED_DOMAINS
  android:
    json:
      - file: app/src/main/assets/capacitor.config.json
        set:
          server:
                allowNavigation: $ALLOWED_DOMAINS
```

The `capacitor.config.json` looks this:
```json
  "server": {
    "allowNavigation": "trapeze.dev,capacitorjs.com"
  },
```

Am I using the array variable wrong or this is not supported?
Thanks.
