### ISSUE TITLE
Copy files

### ISSUE THREAD

**Issue by aktivdigital-frontend** [ionic-team/trapeze#94]
Hi!

Can I copy files with yaml?

For example, I want to copy google-services.json from root to android/app folder.

Thank you!

**Comment by mlynch** [comment]
Not yet but it's definitely easily doable. 

How would you imagine this working? Something like:

```yaml
copy:
  src: /absolute/path/to/file
  dest: ./
```

One question this prompts: should the paths be relative to the android or iOS project or absolute, or both?
