### ISSUE TITLE
Error when parsing strings as environment variables

### ISSUE THREAD

**Issue by leo-jnesis** [ionic-team/trapeze#96]
Steps to reproduce : 
- add a var in your config file without default value : 
```
vars:
  SOME_VERSION:

platform:
  android: 
    versionName: $SOME_VERSION
```
- run `SOME_VERSION="1.2.3" npx trapeze`

You should get this error :  
`Unable to parse environment variable SOME_VERSION SyntaxError: Unexpected token . in JSON at position 3`

This is because we automatically try to parse the variable value as JSON here :
https://github.com/ionic-team/trapeze/blob/cfaeaf892e1565ebb0462d1049ecf9005e0cfe0a/packages/configure/src/ctx.ts#L106
